### ISSUE TITLE
"TypeError: Cannot read property 'createValueMap' of undefined" when trying to store a new permission in MongoDB

### ISSUE THREAD

**Issue by fchristl** [node-casbin/typeorm-adapter#17]
I am using `typeorm-adapter` with a Mongo database as a backend.

I am then simply adding a new permission for a user:

    enforcer.addPermissionForUser('userId', 'objectId', 'action');

While the permission is created in the database, TypeORM's Mongo adapter throws an exception:

```
[0] TypeError: Cannot read property 'createValueMap' of undefined
[0]     at MongoDriver.createGeneratedMap (/Users/.../uApp/packages/uapp-backend/node_modules/typeorm/driver/mongodb/MongoDriver.js:286:40)
[0]     at /Users/.../uApp/packages/uapp-backend/node_modules/typeorm/entity-manager/MongoEntityManager.js:200:79
[0]     at Array.forEach (<anonymous>)
[0]     at MongoEntityManager.<anonymous> (/Users/.../uApp/packages/uapp-backend/node_modules/typeorm/entity-manager/MongoEntityManager.js:198:61)
[0]     at step (/Users/.../uApp/packages/uapp-backend/node_modules/tslib/tslib.js:136:27)
[0]     at Object.next (/Users/.../uApp/packages/uapp-backend/node_modules/tslib/tslib.js:117:57)
[0]     at fulfilled (/Users/.../uApp/packages/uapp-backend/node_modules/tslib/tslib.js:107:62)
[0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

The problem seems to be that `CasbinRule` has no `ObjectID`-annotated property. When I change the declaration of `id` to

    @ObjectIdColumn()
    public id: ObjectID;

, everything works fine.

**Comment by hsluoyz** [comment]
@fchristl thanks for reporting it. Can you make a PR to fix it?

**Comment by fchristl** [comment]
Absolutely. I'll get back to you with one.

**Comment by fchristl** [comment]
Here we go: https://github.com/node-casbin/typeorm-adapter/pull/18

**Comment by hsluoyz** [comment]
Merged.
