### ISSUE TITLE
Error: filtered policies are not supported by this adapter

### ISSUE THREAD

**Issue by vinod827** [node-casbin/typeorm-adapter#24]
Hi all,

This TypeORMAdapter supports FilteredAdapter however not sure why I'm getting below error : -
```
Error: filtered policies are not supported by this adapter
message:"filtered policies are not supported by this adapter"
stack:"Error: filtered policies are not supported by this adapter
    at Enforcer.<anonymous> (/var/task/node_modules/casbin/lib/coreEnforcer.js:159:23)
    at Generator.next (<anonymous>)
    at /var/task/node_modules/casbin/lib/coreEnforcer.js:21:71
    at new Promise (<anonymous>)
    at /var/task/node_modules/casbin/lib/coreEnforcer.js:17:12
    at Enforcer.loadFilteredPolicy (/var/task/node_modules/casbin/lib/coreEnforcer.js:153:16)
    at /var/task/src/loadPermissions.js:35:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runtime.handler (/var/task/index.js:15:22)"
__proto__:Object {constructor: , name: "Error", message: "", …}
```

Below is my code: -
```
'use-strict';
const { newEnforcer } = require('casbin');
const TypeORMAdapter = require('typeorm-adapter');
const { updateCache } = require('./cache-manager/cacheService');
const MODEL = process.env.MODEL || './enforcer/casbin_conf/model.conf';
const { join } = require('path');

module.exports.loadPermissions = async (event, context, callback, logger) => {
    let key = null;
    if (event.queryStringParameters && event.queryStringParameters.key) {
        console.log("Received key: " + event.queryStringParameters.key);
        key = event.queryStringParameters.key;
    }
    const a = await TypeORMAdapter.default.newAdapter({
        type: 'mysql',
        host: '192.168.1.5',
        port: 3306,
        username: 'root',
        password: '',
        database: 'casbin',
    });
    //a.enabledFiltered(true);

    const e = await newEnforcer(join(__dirname, MODEL), a);
    // Load the filtered policy from DB.
    const fp = await e.loadFilteredPolicy({
        'ptype': 'p',
        'v0': 'alice'
    });
    const policies = { "v0": "p", "v1": "admin", "v2": "/*", "v3": "GET" }; //temp code only
    return await updateCache(key, policies, logger);
};
```

I get error whenever I call this method **loadFilteredPolicy()**. Secondly, I would like to know why the method loadFilteredPolicy(filter) is getting called which is there on CoreEnforcer class. I want to invoke the loadFilteredPolicy(model, filter) which is there on TypeORMAdapter.

Please assist me here.

Thank you

**Comment by nodece** [comment]
@vinod827 Could you upgrade to casbin v5.0.3?  It fixed: https://github.com/casbin/node-casbin/commit/a74314d6c4e1e1c8731128e6bfe9e2de1b3f45ce

**Comment by vinod827** [comment]
@nodece this is amazing...thanks it worked for me.
