### ISSUE TITLE
casbin_rule does not exist

### ISSUE THREAD

**Issue by adrianwix** [node-casbin/typeorm-adapter#31]
I have notice this error when trying to run typeorm with "dropSchema" option set to true. I usually just stop the app and start it again and the error disappears. Is there any way to prevent this?

**Comment by hsluoyz** [comment]
Can anyone help on this issue? @nodece @stu01509

**Comment by stu01509** [comment]
@adrianwix 

Can you paste your code and error message? I will get in-depth about this issue.

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
It works fine.
```ts
const a = await TypeORMAdapter.newAdapter({
  type: 'mysql',
  host: 'localhost',
  port: 3306,
  username: 'root',
  password: '*******',
  database: 'casbin',
  dropSchema: true
});
```

**Comment by adrianwix** [comment]
Hi, sorry for not answering. The problem may be that I am calling dropSchema using the Nestjs module. Without calling the adapter with dropSchema. So the adapter tries to access the table after it has been deleted.

Error:
```bash
[Nest] 4696   - 11/01/2020, 5:55:38 PM   [ExceptionHandler] relation "casbin_rule" does not exist +440ms
QueryFailedError: relation "casbin_rule" does not exist
    at new QueryFailedError (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at Query.callback (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:187:38)
    at Query.handleError (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\pg\lib\query.js:128:19)   
    at Client._handleErrorMessage (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\pg\lib\client.js:326:17)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\pg\lib\connection.js:109:12
    at Parser.parse (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\pg-protocol\dist\parser.js:40:17)
    at Socket.<anonymous> (C:\Users\Adrian Wix\Code\posterlab\posterlab-mvp\nest-backend\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:311:20)
```
Nestjs config
```ts
TypeOrmModule.forRootAsync({
            useFactory: (config: ConfigService) => {
                return {
                    type: 'postgres',
                    host: config.get('DATABASE_HOST'),
                    port: config.get<number>('DATABASE_PORT'),
                    username: config.get('DATABASE_USERNAME'),
                    password: config.get('DATABASE_PASSWORD'),
                    database: config.get('DATABASE_NAME'),
                    entities,
                    logging: config.get('NODE_ENV') === 'development',
                    // migrationsRun: config.get('NODE_ENV') !== 'test',
                    dropSchema: true,
                    synchronize: config.get('NODE_ENV') === 'test' || true,
                    migrations: [
                        config.get('NODE_ENV') === 'test'
                            ? join(
                                  __dirname,
                                  '../',
                                  'src/database/migrations/**/*{.ts,.js}',
                              )
                            : join(
                                  __dirname,
                                  'database/migrations/**/*{.ts,.js}',
                              ),
                    ],
                    keepConnectionAlive: true,
                }
            },
            inject: [ConfigService],
        }),
```
Casbin adapter
```ts
{
            provide: CASBIN_ENFORCER,
            useFactory: async (config: ConfigService) => {
                // TODO: Use a different connection
                const adapter = await TypeORMAdapter.newAdapter({
                    type: 'postgres',
                    host: config.get('DATABASE_HOST'),
                    port: config.get<number>('DATABASE_PORT'),
                    username: config.get('DATABASE_USERNAME'),
                    password: config.get('DATABASE_PASSWORD'),
                    database: config.get('DATABASE_NAME'),
                    // dropSchema: true
                })
                // const adapter = join(process.cwd(), 'dist/iam/policy.csv')
                const e = await newEnforcer(
                    join(process.cwd(), 'dist/iam/models/default.conf'),
                    adapter,
                )

                e.addFunction('keyMatch2', keyMatch2Func)
                e.addFunction('keyMatch', keyMatchFunc)

                return e
            },
            inject: [ConfigService],
        },
```

**Comment by nodece** [comment]
@adrianwix Could you try to initialize TypeORM first and then Casbin Adapter?

Maybe adding `dropSchema` is not a good idea :(

**Comment by hsluoyz** [comment]
Closed as stale.
