### ISSUE TITLE
typeORM.newAdapter is not a function

### ISSUE THREAD

**Issue by Fogelman** [node-casbin/typeorm-adapter#9]
Error while creating a new adapter with mysql example. 

`index.js`
```js
const TypeORMAdapter = require("typeorm-adapter");

run = async () => {
  const a = await TypeORMAdapter.newAdapter({
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "root",
    password: "",
    database: "casbin"
  });
};

run();
```

**`error`**
```
(node:6286) UnhandledPromiseRejectionWarning: TypeError: TypeORMAdapter.newAdapter is not a function
    at run (/home/david/Documents/projects/casbin-node/index.js:4:34)
    at Object.<anonymous> (/home/david/Documents/projects/casbin-node/index.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
(node:6286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Fogelman** [comment]
Fixed by modifying the import
```js
const TypeORMAdapter = require("typeorm-adapter").default;
```
